In [26]:
import pandas as pd

In [27]:
df=pd.read_csv("../data/fresh_20k_misleading.csv")
df1=pd.read_csv("../data/checkpoint_fresh_20k.csv")

In [28]:
merge_df = pd.concat([df, df1, ], ignore_index=True)

In [30]:
merge_df.head(20)

,title,text,label,source
0,Conceptually cream skimming has two basic dime...,Conceptually cream skimming has two basic dime...,misleading,NaN
1,yeah i tell you what though if you go price so...,yeah i tell you what though if you go price so...,misleading,NaN
2,But a few Christian mosaics survive above the ...,But a few Christian mosaics survive above the ...,misleading,NaN
3,It's not that the questions they asked weren't...,It's not that the questions they asked weren't...,misleading,NaN
4,"Thebes held onto power until the 12th Dynasty,...","Thebes held onto power until the 12th Dynasty,...",misleading,NaN
5,He turned and smiled at Vrenna.,He turned and smiled at Vrenna. He smiled at V...,misleading,NaN
6,and it's it's quite a bit i think six somethin...,and it's it's quite a bit i think six somethin...,misleading,NaN
7,yeah well you're a student right,yeah well you're a student right Well you're a...,misleading,NaN
8,Were they in there?,Were they in there? Were they supposed to be i...,misleading,NaN
9,When the trust fund begins running cash defici...,When the trust fund begins running cash defici...,misleading,NaN
10,and it is nice talking to you all righty,and it is nice talking to you all righty I tal...,misleading,NaN
11,She smiled back.,She smiled back. She was so happy she couldn't...,misleading,NaN
12,"I did not mention Monica in my lecture, but th...","I did not mention Monica in my lecture, but th...",misleading,NaN
13,Analyzing Postal Service accounts for deprecia...,Analyzing Postal Service accounts for deprecia...,misleading,NaN
14,Because it plays on my childhood imagination.,Because it plays on my childhood imagination. ...,misleading,NaN
15,"At the heart of the sanctuary, a small granite...","At the heart of the sanctuary, a small granite...",misleading,NaN
16,In full costume.,In full costume. He is wearing a mascot costume.,misleading,NaN
17,Although your journey is going to be difficult...,Although your journey is going to be difficult...,misleading,NaN
18,i often think gee i wish i had a video camera ...,i often think gee i wish i had a video camera ...,misleading,NaN
19,In the midst of this amazing amalgam of cultur...,In the midst of this amazing amalgam of cultur...,misleading,NaN

In [31]:
merge_df.info

<bound method DataFrame.info of                                                    title  \
0      Conceptually cream skimming has two basic dime...
1      yeah i tell you what though if you go price so...
2      But a few Christian mosaics survive above the ...
3      It's not that the questions they asked weren't...
4      Thebes held onto power until the 12th Dynasty,...
...                                                  ...
13975  A Fox livestream news report labeled Kyiv a Ru...
13976  NYPD never publicly stated Trump was 5 feet, 1...
13977  Trump's Easter message attacked political oppo...
13978  No proof Pope Francis skipped meeting with JD ...
13979  Speck of dust measures halfway between size of...

                                                    text       label  \
0      Conceptually cream skimming has two basic dime...  misleading
1      yeah i tell you what though if you go price so...  misleading
2      But a few Christian mosaics survive above the ...  misleading
3      It's not that the questions they asked weren't...  misleading
4      Thebes held onto power until the 12th Dynasty,...  misleading
...                                                  ...         ...
13975  Fact Check A Fox livestream news report labele...  misleading
13976  Fact Check NYPD never publicly stated Trump wa...  misleading
13977  Fact Check Trump's Easter message attacked pol...  misleading
13978  Fact Check No proof Pope Francis skipped meeti...  misleading
13979  Fact Check Speck of dust measures halfway betw...  misleading

             source
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
13975  snopes_false
13976  snopes_false
13977  snopes_false
13978  snopes_false
13979  snopes_false

[13980 rows x 4 columns]>

In [32]:
print("Duplicate rows:", merge_df.duplicated().sum())

Duplicate rows: 0

In [33]:
print("Full duplicates:", merge_df.duplicated().sum())
print("Title+Text duplicates:", merge_df.duplicated(subset=['title','text']).sum())

Full duplicates: 0
Title+Text duplicates: 6990

In [39]:
df6 = merge_df.drop_duplicates(subset=['title','text']).reset_index(drop=True)

In [40]:
df6.info

<bound method DataFrame.info of                                                   title  \
0     Conceptually cream skimming has two basic dime...
1     yeah i tell you what though if you go price so...
2     But a few Christian mosaics survive above the ...
3     It's not that the questions they asked weren't...
4     Thebes held onto power until the 12th Dynasty,...
...                                                 ...
6985  A Fox livestream news report labeled Kyiv a Ru...
6986  NYPD never publicly stated Trump was 5 feet, 1...
6987  Trump's Easter message attacked political oppo...
6988  No proof Pope Francis skipped meeting with JD ...
6989  Speck of dust measures halfway between size of...

                                                   text       label source
0     Conceptually cream skimming has two basic dime...  misleading    NaN
1     yeah i tell you what though if you go price so...  misleading    NaN
2     But a few Christian mosaics survive above the ...  misleading    NaN
3     It's not that the questions they asked weren't...  misleading    NaN
4     Thebes held onto power until the 12th Dynasty,...  misleading    NaN
...                                                 ...         ...    ...
6985  Fact Check A Fox livestream news report labele...  misleading    NaN
6986  Fact Check NYPD never publicly stated Trump wa...  misleading    NaN
6987  Fact Check Trump's Easter message attacked pol...  misleading    NaN
6988  Fact Check No proof Pope Francis skipped meeti...  misleading    NaN
6989  Fact Check Speck of dust measures halfway betw...  misleading    NaN

[6990 rows x 4 columns]>

In [41]:
df6['label'] = df6['label'].replace('misleading', 2)

C:\Users\ahmad\AppData\Local\Temp\ipykernel_1636\3158079059.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df6['label'] = df6['label'].replace('misleading', 2)

In [42]:
df6.head(10)

,title,text,label,source
0,Conceptually cream skimming has two basic dime...,Conceptually cream skimming has two basic dime...,2,NaN
1,yeah i tell you what though if you go price so...,yeah i tell you what though if you go price so...,2,NaN
2,But a few Christian mosaics survive above the ...,But a few Christian mosaics survive above the ...,2,NaN
3,It's not that the questions they asked weren't...,It's not that the questions they asked weren't...,2,NaN
4,"Thebes held onto power until the 12th Dynasty,...","Thebes held onto power until the 12th Dynasty,...",2,NaN
5,He turned and smiled at Vrenna.,He turned and smiled at Vrenna. He smiled at V...,2,NaN
6,and it's it's quite a bit i think six somethin...,and it's it's quite a bit i think six somethin...,2,NaN
7,yeah well you're a student right,yeah well you're a student right Well you're a...,2,NaN
8,Were they in there?,Were they in there? Were they supposed to be i...,2,NaN
9,When the trust fund begins running cash defici...,When the trust fund begins running cash defici...,2,NaN

In [43]:
import re

def clean_final(text):
    if pd.isna(text):
        return text

    text = text.lower()

    # ❌ Remove "read more"
    text = re.sub(r'read more', '', text)

    # ❌ Remove URLs
    text = re.sub(r'http\S+', '', text)

    # ❌ Remove multiple dots (...)
    text = re.sub(r'\.{2,}', '.', text)

    # ❌ Remove multiple commas
    text = re.sub(r',+', ',', text)

    # ❌ Remove repeated punctuation (!! ??)
    text = re.sub(r'([!?]){2,}', r'\1', text)

    # ❌ Remove unwanted characters (keep basic punctuation)
    text = re.sub(r'[^a-z0-9\s\.\,\!\?%]', '', text)

    # ❌ Fix spacing around punctuation
    text = re.sub(r'\s*([.,!?])\s*', r'\1 ', text)

    # ❌ Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text
df6['title'] = df6['title'].apply(clean_final)
df6['text'] = df6['text'].apply(clean_final)

In [49]:
df6.head(10)

,title,text,label,source
0,conceptually cream skimming has two basic dime...,conceptually cream skimming has two basic dime...,2,NaN
1,yeah i tell you what though if you go price so...,yeah i tell you what though if you go price so...,2,NaN
2,but a few christian mosaics survive above the ...,but a few christian mosaics survive above the ...,2,NaN
3,its not that the questions they asked werent i...,its that the questions they asked werent inter...,2,NaN
4,"thebes held onto power until the 12th dynasty,...","thebes held onto power until the 12th dynasty,...",2,NaN
5,he turned and smiled at vrenna.,he turned and smiled at vrenna. he smiled at v...,2,NaN
6,and its its quite a bit i think six something ...,and its its quite a bit i think six something ...,2,NaN
7,yeah well youre a student right,yeah well youre a student right well youre a m...,2,NaN
8,were they in there?,were they in there? were they supposed to be i...,2,NaN
9,when the trust fund begins running cash defici...,when the trust fund begins running cash defici...,2,NaN

In [50]:
df6.info

<bound method DataFrame.info of                                                   title  \
0     conceptually cream skimming has two basic dime...
1     yeah i tell you what though if you go price so...
2     but a few christian mosaics survive above the ...
3     its not that the questions they asked werent i...
4     thebes held onto power until the 12th dynasty,...
...                                                 ...
6985  a fox livestream news report labeled kyiv a ru...
6986  nypd never publicly stated trump was 5 feet, 1...
6987  trumps easter message attacked political oppon...
6988  no proof pope francis skipped meeting with jd ...
6989  speck of dust measures halfway between size of...

                                                   text  label source
0     conceptually cream skimming has two basic dime...      2    NaN
1     yeah i tell you what though if you go price so...      2    NaN
2     but a few christian mosaics survive above the ...      2    NaN
3     its that the questions they asked werent inter...      2    NaN
4     thebes held onto power until the 12th dynasty,...      2    NaN
...                                                 ...    ...    ...
6985  fact check a fox livestream news report labele...      2    NaN
6986  fact check nypd publicly stated trump was 5 fe...      2    NaN
6987  fact check trumps easter message attacked poli...      2    NaN
6988  fact check proof pope francis skipped meeting ...      2    NaN
6989  fact check speck of dust measures halfway betw...      2    NaN

[6990 rows x 4 columns]>

In [51]:
ffff=df6.drop(columns=["source"])

In [52]:
ffff.head(10)

,title,text,label
0,conceptually cream skimming has two basic dime...,conceptually cream skimming has two basic dime...,2
1,yeah i tell you what though if you go price so...,yeah i tell you what though if you go price so...,2
2,but a few christian mosaics survive above the ...,but a few christian mosaics survive above the ...,2
3,its not that the questions they asked werent i...,its that the questions they asked werent inter...,2
4,"thebes held onto power until the 12th dynasty,...","thebes held onto power until the 12th dynasty,...",2
5,he turned and smiled at vrenna.,he turned and smiled at vrenna. he smiled at v...,2
6,and its its quite a bit i think six something ...,and its its quite a bit i think six something ...,2
7,yeah well youre a student right,yeah well youre a student right well youre a m...,2
8,were they in there?,were they in there? were they supposed to be i...,2
9,when the trust fund begins running cash defici...,when the trust fund begins running cash defici...,2

In [54]:
mis = ffff[ffff['label'] == 2]

mis_extra = mis.sample(n=8000, replace=True, random_state=42)

ff2 = pd.concat([ffff, mis_extra])

In [56]:
ff2.info

<bound method DataFrame.info of                                                   title  \
0     conceptually cream skimming has two basic dime...
1     yeah i tell you what though if you go price so...
2     but a few christian mosaics survive above the ...
3     its not that the questions they asked werent i...
4     thebes held onto power until the 12th dynasty,...
...                                                 ...
4482  trump lays out new iran strategy friday, compl...
4797  trump stops praising coast guards harvey effor...
6702  doctored photo shows ice agents arresting man ...
5068  did republican sen. john kennedy say trump thw...
5480  did robert de niro say he was leaving nyc beca...

                                                   text  label
0     conceptually cream skimming has two basic dime...      2
1     yeah i tell you what though if you go price so...      2
2     but a few christian mosaics survive above the ...      2
3     its that the questions they asked werent inter...      2
4     thebes held onto power until the 12th dynasty,...      2
...                                                 ...    ...
4482  washington reuters president donald trump will...      2
4797  donald trump has now become well known for his...      2
6702  fact check doctored photo shows ice agents arr...      2
5068  fact check did republican sen. john kennedy sa...      2
5480  fact check did robert de niro say he was leavi...      2

[14990 rows x 3 columns]>

In [53]:
ffff.to_csv("../data/misleadingnew20k.csv",index=False)

In [45]:
import re

def extract_misleading(text):
    if pd.isna(text):
        return None
    
    text = text.lower()

    # ❌ Remove metadata
    text = re.sub(r'written by.*?\d{4}', '', text)
    
    # ❌ Remove "read more"
    text = re.sub(r'read more', '', text)

    # ❌ Remove negation words
    text = re.sub(r"\b(no|not|doesnt|didnt|false|isnt|arent|never)\b", '', text)

    # ❌ Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text


# =========================
# APPLY ON DATASET
# =========================

# If your column is 'text' or 'statement'
df6['text'] = df6['text'].apply(extract_misleading)

# Remove empty rows
df7 = df6.dropna()

# Remove very short rows (important)
df8 = df7[df7['text'].str.len() > 20]

# =========================
# SAVE
# =========================
# df.to_csv("misleading_converted.csv", index=False)
df8.to_csv("../data/finaldatasets/misleadingfile2.csv", index=False, encoding="utf-8-sig")

print("Done ✅", df.shape)

Done ✅ (6990, 3)

In [46]:
df8.head(20)

Empty DataFrame
Columns: [title, text, label, source]
Index: []

In [47]:
df8['text'] = df8['text'].str.replace(r'\bfact check\b', '', regex=True)
df8['text'] = df8['text'].str.replace(r'\s+', ' ', regex=True).str.strip()
df8.to_csv("../data/finaldatasets/misleadingfile.csv", index=False, encoding="utf-8-sig")

In [23]:
import csv
df6.to_csv("../data/finaldatasets/misleadingfile.csv", index=False, encoding="utf-8-sig", quoting=csv.QUOTE_ALL)